language: rust
sudo: false
cache: cargo

rust:
  - stable

services:
  - docker

env:
  global:
    - RUST_TEST_THREADS: 1
    - CARGO_TERM_COLOR: always

script: |
  echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin &&
  cargo build &&
  ./tests/run-all-tests $KAFKA_VER &&
  cargo doc

jobs:
  include:
    # 0.8 doesn't support secure settings
    - env: KAFKA_VER=0.8.2.2 COMPRESSIONS=NONE SECURES=
    - env: KAFKA_VER=0.8.2.2 COMPRESSIONS=SNAPPY SECURES=
    - env: KAFKA_VER=0.8.2.2 COMPRESSIONS=GZIP SECURES=

    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=NONE SECURES=
    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=NONE SECURES=secure
    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=SNAPPY SECURES=
    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=SNAPPY SECURES=secure
    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=GZIP SECURES=
    - env: KAFKA_VER=0.9.0.1 COMPRESSIONS=GZIP SECURES=secure

    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=NONE SECURES=
    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=NONE SECURES=secure
    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=SNAPPY SECURES=
    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=SNAPPY SECURES=secure
    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=GZIP SECURES=
    - env: KAFKA_VER=0.10.2.1 COMPRESSIONS=GZIP SECURES=secure

    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=NONE SECURES=
    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=NONE SECURES=secure
    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=SNAPPY SECURES=
    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=SNAPPY SECURES=secure
    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=GZIP SECURES=
    - env: KAFKA_VER=0.11.0.1 COMPRESSIONS=GZIP SECURES=secure

    - env: KAFKA_VER=1.0.0 COMPRESSIONS=NONE SECURES=
    - env: KAFKA_VER=1.0.0 COMPRESSIONS=NONE SECURES=secure
    - env: KAFKA_VER=1.0.0 COMPRESSIONS=SNAPPY SECURES=
    - env: KAFKA_VER=1.0.0 COMPRESSIONS=SNAPPY SECURES=secure
    - env: KAFKA_VER=1.0.0 COMPRESSIONS=GZIP SECURES=
    - env: KAFKA_VER=1.0.0 COMPRESSIONS=GZIP SECURES=secure
