[package]
name = "kafka"
version = "0.9.0"
authors = ["Yousuf Fauzan", "Petr Novotnik <pnovotnik@googlemail.com>", "John Ward <john@johnward.net>"]
description = "Rust client for Apache Kafka"
homepage = "https://github.com/kafka-rust/kafka-rust"
repository = "https://github.com/kafka-rust/kafka-rust"
documentation = "https://docs.rs/kafka/"
readme = "README.md"
keywords = ["kafka", "queue"]
license = "MIT"
edition = "2018"

[dependencies]
byteorder = "1.4.1"
crc = "2.0.0"
log ="0.4.14"
ref_slice = "1.0"
fnv = "1.0"
twox-hash = "1.1"
error-chain = "0.12.3"

flate2 = { version = "1.0.19", optional = true }
snap = { version = "1", optional = true }
openssl = { version = "0.10", optional = true }
zstd = { version="0.9.0", optional = true }

[dev-dependencies]
getopts = "0.2"
env_logger = "0.9"
time = "0.2"
rand = "0.8.2"
lazy_static = "1.3.0"


[features]
default = ["snappy", "gzip", "zstandard", "security"]
snappy = ["snap"]
gzip = ["flate2"]
zstandard = ["zstd"]
security = ["openssl"]
nightly = []
integration_tests = []
